# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Descripction', models.CharField(max_length=250)),
                ('QuantityAvaliable', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
