# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20171128_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentmovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequireDate', models.DateField()),
                ('DeliveryDate', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Cost', models.FloatField()),
                ('Status', models.IntegerField(choices=[(1, 'Available'), (2, 'Rented'), (3, 'Out-Stock')], default=1)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.movies')),
            ],
        ),
    ]
