# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rentmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentmovie',
            name='User',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
